spring:
  datasource:
    username: postgres
    password: 123456
    #    url: jdbc:postgresql://127.0.0.1:5432/sdw_test1
    url: jdbc:postgresql://127.0.0.1:5432/sdw
    driver-class-name: org.postgresql.Driver
#    type: com.alibaba.druid.pool.DruidDataSource #切换数据源
    # 初始化大小，最小，最大
#    initialSize: 1
#    minIdle: 3
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    #    控制台显示SQL
    show-sql: true
    hibernate:
      #      更新或者创建数据表
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#server:
#  tomcat:
#    uri-encoding: UTF-8
#日志
logging:
  level:
    com:
      example: trace
  file:
    path: /spring/log
#redis
redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
